#!/bin/bash
source ./setup.sh || exit 1

###############################################################################
# This runs the simulation - a simple pointed observation.
#
# The radec2xy tool is needed to add information used for region filtering
# to the event file.
#
# Note that this simulation runs rather slowly, due to the large number of
# sources.
###############################################################################


sixtesim RA=${RA} Dec=${DEC} \
  Simput=${OUTDIR}/cluster_3D.simput \
  Exposure=${EXP} \
  XMLFile=${XML} \
  Prefix=${OUTDIR}/${STEM}_ \
  Background=n clobber=y

radec2xy \
  EvtFile=${OUTDIR}/${STEM}_evt.fits \
  Projection=TAN \
  RefRA=$RA RefDec=$DEC
