#!/bin/bash

################################################################################
# Get data for the multicell and multispec examples
################################################################################

if [ ! -f input/wabs_vapc_cosmo.xcm ] ; then
  # fetch data and unpack
  wget https://www.sternwarte.uni-erlangen.de/~sixte/downloads/X-IFU_clusters_tutorial.tgz
  tar -xzvf X-IFU_clusters_tutorial.tgz

  # move relevant files to input folder
  mv X-IFU_clusters_tutorial/wabs_vapec_cosmo.xcm input/
  mv X-IFU_clusters_tutorial/xifu_3D_grid.fits input/

  # also move the files for multispec
  mv X-IFU_clusters_tutorial/xifu_point_source.xcm ../multispec/input/phabs_apec.xcm
  mv X-IFU_clusters_tutorial/A2146_*.fits ../multispec/input/

  # cleanup
  rm -rf X-IFU_clusters_tutorial X-IFU_clusters_tutorial.tgz
fi
