#!/bin/bash

source ./setup.sh || exit 1

# Test script to verify a recent version of simput is available

# have simput?
if [ -z "${SIMPUT}" ] ; then
  echo "***error: No simput found in \$SIMPUT!" >&2
  exit 1
fi

SIMPUTVERSION=$(which simputversion)

if [ -z "${SIMPUTVERSION}" ] ; then
  echo "***error: No 'simputersion in \$PATH! Did you source the install script?"
  exit 1
fi

VERSION=$("${SIMPUTVERSION}")

set -- ${VERSION}
VERSION="$3"
IFS='.' read -r major minor patch <<< "${VERSION}"

IFS='.' read -r tmajor tminor tpatch <<< "${SIMPUT_VERSION}"

# have valid version?
if [ "$major" -lt "$tmajor" ] || [ "$minor" -lt "$tminor" ] || [ "$patch" -lt "$tpatch" ]; then
  echo "***error: simput version '${VERSION}' is too old (must be at least ${SIIMPUT_VERSION})!" >&2
  exit 1
fi
