#!/bin/bash

source ./setup.sh || exit 1

# Test if valid sixte version is available

# have sixte?
if [ -z "${SIXTE}" ] ; then
  echo "***error: No sixte found in \$SIXTE!" >&2
  exit 1
fi

SIXTEVERSION=$(which sixteversion)

if [ -z "${SIXTEVERSION}" ] ; then
  echo "***error: No 'sixteversion' in \$PATH! Did you source the install script?"
  exit 1
fi

VERSION=$("${SIXTEVERSION}")

set -- ${VERSION}
VERSION="$3"

IFS='.' read -r major minor patch <<< "${VERSION}"

IFS='.' read -r tmajor tminor tpatch <<< "${SIXTE_VERSION}"

# have valid version?
if [ "${major}" -lt "${tmajor}" ] || [ "${minor}" -lt "${tminor}" ] || [ "${patch}" -lt "${tpatch}" ] ; then
  echo "***error: sixte version '${VERSION}' is to old (must be at least '${SIXTE_VERSION})!'" >&2
  exit 1
fi
