#!/bin/bash

source ./setup.sh || exit 1

simputfile \
  RA=${RA} Dec=${DEC} \
  srcFlux="2.8e-13" \
  Emin=2 Emax=10 \
  Nbin=1000 \
  XSPECFile=input/plaw.xcm \
  clobber=yes chatter=0 \
  Simput=${OUTDIR}/dummy.simput \
  || exit 1
