#!/bin/bash

TARGETVERSION='0.0.0'

# Test if Athena XIFU file is available
SIXTE_INSTRUMENTS="${SIXTE_INSTRUMENTS:-${SIXTE}/share/sixte/instruments}"
FILE="${SIXTE_INSTRUMENTS}/athena-xifu/baseline"

# have baseline dir?
if [ ! -d "${FILE}" ] ; then
  echo "***error: No directory for Athena/XIFU found!" >&2
  exit 1
fi

# No version file :(
#VERSION=$(cat "${FILE}")
#IFS='.' read -r major minor patch <<< "${VERSION}"

#IFS='.' read -r tmajor tminor tpatch <<< "${TARGETVERSION}"

#if [ ${major} -lt ${tmajor} ] || [ ${minor} -lt ${tminor} ] || [ ${patch} -lt ${tpatch} ] ; then
#  echo "***error: Athena/XIFU version files are too old ('${VERSION}'). Required is at least version '${TARGETVERSION}'." >&2
#  exit 1
#fi
