#!/bin/bash

#############################################
# The following script will generate an image of the event file.
# Make sure to fill the areas marked as "__?___".
############################################

base=___?___

$SIXTE/bin/imgev \
	EvtFile=sim_evt_${base}.fits \
	Image=img_${base}.fits \
	CoordinateSystem=0 Projection=TAN \
	NAXIS1=512 NAXIS2=512 \
	CUNIT1=deg CUNIT2=deg \
	CRVAL1=__?__ CRVAL2=__?___ \
	CRPIX1=256.5 CRPIX2=256.5 \
	CDELT1=-6.207043e-04 CDELT2=-6.207043e-04 \
	history=true clobber=yes
