#!/bin/bash

TARGETVERSION='1.11.4'

# Test if Athena/WFI version file is available
SIXTE_INSTRUMENTS="${SIXTE_INSTRUMENTS:-${SIXTE}/share/sixte/instruments}"
FILE="${SIXTE_INSTRUMENTS}/athena-wfi.version"

# have version file?
if [ ! -f "${FILE}" ] ; then
  echo "***error: No version file for Athena/WFI found!" >&2
  exit 1
fi

VERSION=$(cat "${FILE}")
IFS='.' read -r major minor patch <<< "${VERSION}"

IFS='.' read -r tmajor tminor tpatch <<< "${TARGETVERSION}"

if [ ${major} -lt ${tmajor} ] || [ ${minor} -lt ${tminor} ] || [ ${patch} -lt ${tpatch} ] ; then
  echo "***error: Athena/WFI version files are too old ('${VERSION}'). Required is at least version '${TARGETVERSION}'." >&2
  exit 1
fi
