#!/bin/bash

# Check existance of xml files
SIXTE_INSTRUMENTS=${SIXTE_INSTRUMENTS:-"${SIXTE}/share/sixte/instruments"}

FILELIST="xifu_nofilt_defoc.xml \
xifu_nofilt_infoc.xml \
xifu_be_filter_defoc.xml \
xifu_be_filter_infoc.xml \
xifu_optical_filter_defoc.xml \
xifu_optical_filter_infoc.xml"

for f in ${FILELIST} ; do
  ff="${SIXTE_INSTRUMENTS}/new-athena-xifu/baseline/${f}"
  # have instrument file?
  if [ ! -f "${ff}" ] ; then
    echo "***error: No file '${ff}', but should be there!" >&2
    exit 1
  fi
done

FILELIST="derivative_xt_LPA50x30_20250915.fits
mut_ind_xt_LPA50x30_20250915.fits
new_athena_xifu_rb_30eV_gaussian.rmf
new_athena_xifu_rb_3d1eV_gaussian.rmf
new_athena_xifu_rb_3d6eV_gaussian.rmf
new_athena_xifu_rb_3eV_gaussian.rmf
new_athena_xifu_rb_4d2eV_gaussian.rmf
new_athena_xifu_rb_4eV_gaussian.rmf
new_athena_xifu_rb_5eV_gaussian.rmf
new_athena_xifu_rb_7eV_gaussian.rmf
new_athena_xifu_rb_be_filter_100um.arf
new_athena_xifu_rb_no_filter.arf
new_athena_xifu_rb_nxb_sixte.pha
new_athena_xifu_rb_optical_filter.arf
new_athena_xifu_rb_psf_defoc_20250915.fits
new_athena_xifu_rb_psf_hew9_20250915.fits
new_athena_xifu_rb_vig_20250915.fits
proportional_xt_LPA50x30_20250915.fits
thermal_xt_diagonal_time_dep_20250915.fits
thermal_xt_nearest_time_dep_20250915.fits
thermal_xt_second_time_dep_20250915.fits"

for f in ${FILELIST} ; do
  ff="${SIXTE_INSTRUMENTS}/new-athena-xifu/instdata/${f}"
  # have instrument file?
  if [ ! -f "${ff}" ] ; then
    echo "***error: No file '${ff}', but should be there!" >&2
    exit 1
  fi
done
