#!/bin/bash

source ./setup.sh || exit 1

###############################################################################
# This script builds two SIMPUTs using the two images defined in the previous
# script.
# Each hemisphere is assigned a different spectrum.
###############################################################################

sides=(east west)
specs=(soft hard)

for ii in ${!sides[@]}
do
  side=${sides[$ii]}
  spec=${specs[$ii]}

  simputfile \
    Simput=${OUTDIR}/${STEM}_${spec}.simput \
    Src_ID=$(($ii + 1)) \
    RA=${RA} Dec=${DEC} \
    srcFlux=2e-11 Emin=2 Emax=10 \
    Elow=0.1 Eup=15 Nbins=14900 \
    XSPECFile=input/model_${spec}.xcm \
    ImageFile=${OUTDIR}/${STEM}_simput_img_${side}.fits \
    clobber=y
done
