#!/bin/bash

source ./setup.sh || exit 1

# Create several simputs with different flux levels

FLUXES="2e-16 5e-16 1e-15 2e-15 5e-15 1e-14 \
2e-14 5e-14 1e-13 2e-13 5e-13 1e-12 \
2e-12 5e-12 1e-11 2e-11 5e-11 1e-10 
2e-10 5e-10 1e-09 2e-09"

# get the NVALID number from the events file
CALIBCOUNTS=$(fkeyprint ${OUTDIR}/${STEM}_base_evt.fits[1] NVALID | grep 'NVALID  =')
set -- ${CALIBCOUNTS}
CALIBCOUNTS=$3

rm -f ${OUTDIR}/exposure_list.dat
for f in ${FLUXES} ; do
  python write_exposure_list.py ${CALIBCOUNTS} ${EXP} ${f} 2.4e-12
done

for f in ${FLUXES} ; do
  simputfile \
    Simput=${OUTDIR}/pointsrc_flux${f}.simput \
    RA=${RA} Dec=${DEC} \
    XSPECFile=input/plaw.xcm \
    Elow=0.1 Eup=15 Nbins=1000 \
    logEgrid=n \
    Emin=2 Emax=10 srcFlux=${f} \
    clobber=y
done
