#!/bin/bash

source ./setup.sh || exit 1  

# sixtesim [....] MJDREF=55000
# - note: we need the same MJDREF when creating the light curve,
#    need to 'observe' during the same absolute time in which we
#    defined the light curve
# - use "plist runsixt" to have a look at the input parameters

sixtesim  \
  Prefix=${OUTDIR}/sim_twosources_ \
  [....]

# note: you can use ds9 (or fv) to view the event file as an image
# (not on sciserver, though)
