#!/bin/bash

source ./setup.sh || exit 1

#############################################
# The following script will generate a SIMPUT file for a single point source.
############################################

base=mcrab 

$SIMPUT/bin/simputfile \
	Simput=${base}.fits \
	Src_Name=first \
	RA=0.0 Dec=0.0 \
	srcFlux=2.1157e-11 \
	Elow=0.1 Eup=15 \
	Nbins=1000 \
	logEgrid=yes \
	Emin=2 Emax=10 \
	XSPECFile= input/${base}.xcm \
	clobber=yes

