#!/bin/bash

source ./setup.sh || exit 1

#############################################
# The following script will generate a simulated event file.
############################################

base=mcrab

$SIXTE/bin/sixtesim \
	XMLFile =${XML} \
	RA=0.000 Dec=0.000 \
	Prefix=sim_ \
	Simput=${base}.fits \
	EvtFile=evt_${base}.fits \
	Exposure=1000
