#!/bin/bash

source ./setup.sh || exit 1

#############################################
# The following script will generate an image of the event file.
# Imgev parameter values are instrument specific, here we use single Athena-WFI chip.
############################################

base=mcrab

$SIXTE/bin/imgev \
	EvtFile=sim_evt_${base}.fits \
	Image=img_${base}.fits \
	CoordinateSystem=0 Projection=TAN \
	NAXIS1=512 NAXIS2=512 \
	CUNIT1=deg CUNIT2=deg \
	CRVAL1=0.0 CRVAL2=0.0 \
	CRPIX1=256.5 CRPIX2=256.5 \
	CDELT1=-6.207043e-04 CDELT2=-6.207043e-04 \
	history=true clobber=yes
