#!/bin/bash

source ./setup.sh || exit 1

#############################################
# The following script will generate a light curve by first creating a new event file.
############################################

base=mcrab_lightcurve

$SIMPUT/bin/simputfile \
	Simput=${base}.fits \
	Src_Name=first \
	RA=0.0 Dec=0.0 \
	srcFlux=2.1157e-11 \
	Elow=0.1 Eup=15 \
	Nbins=1000 \
	logEgrid=yes \
	Emin=2 Emax=10 \
	MJDREF=55000 \
	LCFile=input/example_lightcurve.dat \
	XSPECFile=input/mcrab.xcm \
	clobber=yes

$SIXTE/bin/sixtesim \
	XMLFile =${XML} \
	RA=0.000 Dec=0.000 \
	Prefix=sim_ \
	Simput=${base}.fits \
	EvtFile=evt_${base}.fits \
	Exposure=1000

$SIXTE/bin/makelc \
	EvtFile=sim_evt_${base}.fits \
	Lightcurve=sim_${base}.lc \
	length=1000.0 \
	dt=1.0

