#!/bin/bash
source ./setup.sh || exit 1

###############################################################################
# This script extracts one spectrum per region - simple enough.
###############################################################################

for reg in cen out; do

  makespec EvtFile=${OUTDIR}/${STEM}_evt.fits \
    RSPPATH=${INSTRUMENT_PATH} \
    regfile=input/${INSTRUMENT}_${reg}.reg \
    Spectrum=${OUTDIR}/${STEM}_${reg}.pha \
    clobber=y

done
