#!/bin/bash

source ./setup.sh || exit 1

###############################################################################
# This call to simputfile is relatively standard, aside from the use of the
# LCFile and LCPeriod variables.
###############################################################################

simputfile \
  Simput=${OUTDIR}/${STEM}.simput \
  RA=$RA Dec=$DEC \
  srcFlux=2e-11 Emin=2 Emax=10 \
  Elow=0.1 Eup=15 Nbins=1000 logEgrid=y \
  XSPECFile=./input/mcrab.xcm \
  LCFile=input/lc.txt LCPeriod=10 \
  clobber=y
